# Generated by Django 3.1.1 on 2020-09-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('companyLocation', models.CharField(max_length=100)),
                ('websiteLink', models.URLField(blank=True, null=True)),
                ('companyContact', models.CharField(max_length=250)),
                ('applicationWay', models.CharField(choices=[('TE', 'Telefoon'), ('EM', 'E-mail'), ('PE', 'Persoonlijk')], default='EM', max_length=50)),
                ('dateApplication', models.DateField(blank=True, null=True)),
                ('dateReaction', models.DateField(blank=True, null=True)),
                ('dateFaceToFace', models.DateField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('reasonRejected', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
