# Generated by Django 3.1.1 on 2020-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='websiteLink',
            field=models.URLField(null=True),
        ),
    ]
