# Generated by Django 3.1.1 on 2020-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200914_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateApplication',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateFaceToFace',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateReaction',
            field=models.DateField(null=True),
        ),
    ]
